// This file is generated by Slice Machine. Update with care!

import Main from './Main';
import MySlice from './MySlice';

export {
	Main,
	MySlice,
};

export const components = {
	main: Main,
	my_slice: MySlice,
};
